// AUTO-GENERATED by scripts/gen_ts.py — do not edit by hand.
// Source of truth: agentix/contracts/*.schema.json + constants/cluster.yaml.
// Regenerate with `python scripts/gen_ts.py` after any contract/cluster change.
// Client-safe: enums + lifecycle labels only (no broker/NATS internals).

// ── Migration lifecycle — constants/cluster.yaml :: migration.states ──
export const MIGRATION_STATES = Object.freeze(["Approved", "Queued", "Migrating", "Test", "Gap-fix", "Delivered", "Deployed"])

// Human label for a state_index; falls back to `State N` out of range.
export function migrationStateLabel(index) {
  return MIGRATION_STATES[index] ?? `State ${index}`
}

// ── Contract B enums — contracts/*.schema.json ──
export const JobType = Object.freeze({
  MIGRATE: "migrate",
  DRY_RUN: "dry_run",
  ESTIMATE: "estimate",
  BULK_LOAD: "bulk_load",
  ROLLBACK: "rollback",
  VERIFY: "verify",
  PORT_MODULE: "port_module",
  TRAJECTORIES_REBUILD: "trajectories_rebuild",
  DISCOVER_ORDER: "discover_order",
  BACKFILL_TYPES: "backfill_types",
})

export const EventType = Object.freeze({
  SESSION_STARTED: "session_started",
  SESSION_END: "session_end",
  MODEL_STARTED: "model_started",
  MODEL_COMPLETED: "model_completed",
  JOB_STARTED: "job_started",
  JOB_COMPLETED: "job_completed",
  JOB_FAILED: "job_failed",
  TURN_STARTED: "turn_started",
  TURN_COMPLETED: "turn_completed",
  SAFETY_EVENT: "safety_event",
  CHECKPOINT_REQUESTED: "checkpoint_requested",
  VERIFY_STAGE: "verify_stage",
})
