#!/usr/bin/env python3
"""gen_shared.py — generate the canonical shared Python module from the contracts.

Single source of truth: `contracts/*.schema.json` (the wire types) + `constants/cluster.yaml`
(the broker subjects/streams). This script emits `libs/python/ludo_shared/_generated.py` so
the Python repos stop hand-maintaining parallel copies of `JobType` / event types / broker
constants (CRIE R-2, R-4, C-5).

Consumers VENDOR the generated `ludo_shared/` package (byte-identical copy) the same way they
vendor `contracts/` and `constants/cluster.yaml`; drift is guarded by check_shared_drift.py.

Run: `python scripts/gen_shared.py` (needs PyYAML). Re-run after any contract/cluster change.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
CONTRACTS = REPO / "contracts"
CLUSTER = REPO / "constants" / "cluster.yaml"
OUT = REPO / "libs" / "python" / "ludo_shared" / "_generated.py"


def _enum_block(name: str, values: list[str], doc: str) -> str:
    """Render a StrEnum whose member names are the upper-cased values."""
    members = "\n".join(f'    {v.upper()} = "{v}"' for v in values)
    return f'class {name}(StrEnum):\n    """{doc}"""\n\n{members}\n'


def main() -> int:
    cluster = yaml.safe_load(CLUSTER.read_text(encoding="utf-8"))
    broker = cluster["broker"]
    subjects, streams = broker["subjects"], broker["streams"]

    job = json.loads((CONTRACTS / "job-message.schema.json").read_text(encoding="utf-8"))
    event = json.loads((CONTRACTS / "session-event.schema.json").read_text(encoding="utf-8"))
    job_types = job["properties"]["type"]["enum"]
    event_types = event["properties"]["type"]["enum"]

    parts: list[str] = [
        '"""AUTO-GENERATED by scripts/gen_shared.py — do not edit by hand.',
        "",
        "Source of truth: ludo-init/contracts/*.schema.json + constants/cluster.yaml.",
        "Regenerate with `python scripts/gen_shared.py` after any contract/cluster change.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from enum import StrEnum",
        "from typing import Any",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
        "# ── Broker (NATS JetStream) — from constants/cluster.yaml :: broker ───────────",
        f'NATS_URL = "{broker["url"]}"',
        f'JOBS_SUBJECT = "{subjects["jobs"]}"',
        f'JOBS_CANCEL_SUBJECT = "{subjects["jobs_cancel"]}"',
        f'EVENTS_SUBJECT_PREFIX = "{subjects["events_prefix"]}"  # ludo.events.<session_id>',
        f'JOBS_STREAM = "{streams["jobs"]}"',
        f'EVENTS_STREAM = "{streams["events"]}"',
        "",
        "",
        "def event_subject(session_id: str) -> str:",
        '    """Per-session egress subject for Contract B events."""',
        "    return f\"{EVENTS_SUBJECT_PREFIX}.{session_id or 'unknown'}\"",
        "",
        "",
        "# ── Contract B enums — from contracts/*.schema.json ──────────────────────────",
        _enum_block("JobType", job_types, "Dispatch key (gateway -> agent). Mirror of the job-message schema."),
        "",
        _enum_block("EventType", event_types, "Session-event type (agent -> gateway). Mirror of the session-event schema."),
        "",
        "EVENT_TYPES = frozenset(EventType)",
        "",
        "",
        "# ── Contract B models ────────────────────────────────────────────────────────",
        "class JobMessage(BaseModel):",
        '    """gateway -> agent broker payload (ludo.jobs). additionalProperties: false."""',
        "",
        '    model_config = ConfigDict(extra="forbid")',
        "",
        "    job_id: str",
        "    type: JobType",
        "    account_id: str",
        "    idempotency_key: str | None = None",
        "    session_id: str | None = None",
        "    source: dict[str, Any] | None = None",
        "    target: dict[str, Any] | None = None",
        "    source_version: str | None = None",
        "    target_version: str | None = None",
        "    params: dict[str, Any] = Field(default_factory=dict)",
        "    budget_usd: float | None = None",
        "",
        "",
        "class SessionEvent(BaseModel):",
        '    """agent -> gateway event envelope (ludo.events.<session_id>). extra allowed."""',
        "",
        '    model_config = ConfigDict(extra="allow")',
        "",
        "    session_id: str",
        "    type: EventType",
        "    payload: dict[str, Any] = Field(default_factory=dict)",
        "    at: str",
        "    schema_version: str",
        "    checkpoint_required: bool = False",
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"[ok] wrote {OUT.relative_to(REPO)} "
          f"({len(job_types)} job types, {len(event_types)} event types)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
